#
# Vivado (TM) v2015.4.1 (64-bit)
#
# zc706_test.tcl: Tcl script for re-creating project 'top'
#
# Generated by Vivado on Thu Apr 07 21:05:41 JST 2016
# IP Build 1427053 on Mon Dec  7 12:56:29 MST 2015
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (zc706_test.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "/home/aom/work/zynq_work/ether10g_zynq/cores/xgmiisync/rtl/xgmiisync.v"
#    "/home/aom/work/zynq_work/ether10g_zynq/boards/zc706/rtl/network_path/ten_gig_eth_pcs_pma_ip_GT_Common_wrapper.v"
#    "/home/aom/work/zynq_work/ether10g_zynq/boards/zc706/synthesis/runs/top.srcs/sources_1/ip/ten_gig_eth_pcs_pma_ip/ten_gig_eth_pcs_pma_ip.xci"
#    "/home/aom/work/zynq_work/ether10g_zynq/cores/crc32/rtl/CRC32_D64.v"
#    "/home/aom/work/zynq_work/ether10g_zynq/boards/zc706/rtl/network_path/xgbaser_gt_same_quad_wrapper.v"
#    "/home/aom/work/zynq_work/ether10g_zynq/boards/zc706/rtl/network_path/network_path.v"
#    "/home/aom/work/zynq_work/ether10g_zynq/boards/zc706/rtl/app.v"
#    "/home/aom/work/zynq_work/ether10g_zynq/boards/zc706/rtl/top.v"
#    "/home/aom/work/zynq_work/ether10g_zynq/boards/zc706/rtl/clock_control/kcpsm6.vhd"
#    "/home/aom/work/zynq_work/ether10g_zynq/boards/zc706/rtl/clock_control/clock_control_program.vhd"
#    "/home/aom/work/zynq_work/ether10g_zynq/boards/zc706/rtl/clock_control/clock_control.vhd"
#    "/home/aom/work/zynq_work/ether10g_zynq/boards/zc706/constraints/zc706.xdc"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "zc706_test.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/runs"]"

# Create project
create_project top ./top

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [get_projects top]
set_property "default_lib" "xil_defaultlib" $obj
set_property "part" "xc7z045ffg900-2" $obj
set_property "sim.ip.auto_export_scripts" "1" $obj
set_property "simulator_language" "Mixed" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../../cores/xgmiisync/rtl/xgmiisync.v"]"\
 "[file normalize "$origin_dir/../rtl/network_path/ten_gig_eth_pcs_pma_ip_GT_Common_wrapper.v"]"\
 "[file normalize "$origin_dir/runs/top.srcs/sources_1/ip/ten_gig_eth_pcs_pma_ip/ten_gig_eth_pcs_pma_ip.xci"]"\
 "[file normalize "$origin_dir/../../../cores/crc32/rtl/CRC32_D64.v"]"\
 "[file normalize "$origin_dir/../rtl/network_path/xgbaser_gt_same_quad_wrapper.v"]"\
 "[file normalize "$origin_dir/../rtl/network_path/network_path.v"]"\
 "[file normalize "$origin_dir/../rtl/app.v"]"\
 "[file normalize "$origin_dir/../rtl/top.v"]"\
 "[file normalize "$origin_dir/../rtl/clock_control/kcpsm6.vhd"]"\
 "[file normalize "$origin_dir/../rtl/clock_control/clock_control_program.vhd"]"\
 "[file normalize "$origin_dir/../rtl/clock_control/clock_control.vhd"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/../rtl/clock_control/kcpsm6.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../rtl/clock_control/clock_control_program.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/../rtl/clock_control/clock_control.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "top" $obj
set_property "verilog_define" "USE_VIVADO=1" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/../constraints/zc706.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/../constraints/zc706.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "top" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7z045ffg900-2 -flow {Vivado Synthesis 2015} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2015" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "part" "xc7z045ffg900-2" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7z045ffg900-2 -flow {Vivado Implementation 2015} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2015" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "part" "xc7z045ffg900-2" $obj
set_property "steps.phys_opt_design.is_enabled" "1" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:top"
